# Generated by Django 4.0.3 on 2022-03-07 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_roleuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roleuser',
            old_name='role',
            new_name='roles',
        ),
    ]
