# Generated by Django 4.0.3 on 2022-03-07 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_role_roleuser_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleuser',
            name='role',
            field=models.ForeignKey(default='Supervisor', on_delete=django.db.models.deletion.DO_NOTHING, to='users.role'),
        ),
    ]
