# Generated by Django 4.0.3 on 2022-03-07 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_roleuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='role')),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='address')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='country')),
                ('phone', models.BigIntegerField(blank=True, null=True, verbose_name='phone number')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.group')),
            ],
            options={
                'db_table': 'building',
            },
        ),
    ]
